<html>
<head>
	<title>User sign up</title>
	<meta charset="utf-8">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-2 col-sm-2 col-xs-0"></div>
			<div class="col-md-8 col-sm-8 col-xs-12">
				<div class="page-header">
		  			<h1>Sign up</h1>
				</div>


				<?php if (!empty($errorList)) : ?>
					<?php foreach ($errorList as $currentError) : ?>
						<?= $currentError ?><br>
					<?php endforeach ; ?>
				<?php endif ; ?>

	
				<form method="post" action="">
					<fieldset>
						<input type="email" class="form-control" name="emailToto" value="" placeholder="Email address" /><br />
						<input type="password" class="form-control" name="passwordToto1" value="" placeholder="Your password" /><br />
						<input type="password" class="form-control" name="passwordToto2" value="" placeholder="Confirm your password" /><br />
						<input type="submit" class="btn btn-success btn-block" value="Sign up" />
					</fieldset>
				</form>
				<?= date('d/m/Y')?>
			</div>
			<div class="col-md-2 col-sm-2 col-xs-0"></div>
		</div>

	</div>

</body>
</html>